"""empty message

Revision ID: b9bf48253735
Revises: 
Create Date: 2023-06-26 01:31:04.098154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bf48253735'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_user',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('auction',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('buyout_price', sa.Double(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('owner_name', sa.String(length=50), nullable=False),
    sa.Column('bought_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['bought_by'], ['auction_user.name'], ),
    sa.ForeignKeyConstraint(['owner_name'], ['auction_user.name'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('bid',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('amt', sa.Double(), nullable=False),
    sa.Column('owner_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_name'], ['auction_user.name'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('auction_bid_link',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auction._id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bid_id'], ['bid._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_bid_link')
    op.drop_table('bid')
    op.drop_table('auction')
    op.drop_table('auction_user')
    # ### end Alembic commands ###
